[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
apkmirror-arch = "arm64-v8a"
build-mode = "module"
included-patches = "'Remove player controls background'"
excluded-patches = "'HDR auto brightness' 'Remember video quality' 'Vanced MicroG support' 'Enable debugging' 'Hide timestamp' 'Hide 'Load more' button' 'Comments' 'Hide seekbar' 'Disable auto captions' 'Enable tablet layout' 'Premium heading' 'Return YouTube Dislike' 'Tablet mini player' 'Spoof app version' 'Alternative thumbnails'"
